export const COPY = {
  app: {
    name: 'POLOLITOTRABAJOS',
    tagline: 'Encuentra tu maestro para cualquier trabajo',
  },
  tabs: {
    maestros: 'Maestros',
    publicar: 'Publicar',
    chats: 'Chats',
    perfil: 'Perfil',
  },
  auth: {
    welcome_title: 'Bienvenido a POLOLITOTRABAJOS',
    welcome_subtitle: 'Conectamos clientes con maestros de confianza, al tiro.',
    login: 'Iniciar sesión',
    register: 'Registrarse',
    role_title: '¿Qué buscai?',
    role_cliente: 'Busco un maestro',
    role_cliente_desc: 'Necesito que me hagan una pega',
    role_maestro: 'Soy maestro',
    role_maestro_desc: 'Quiero ofrecer mis servicios',
    email_label: 'Tu email',
    nombre_label: 'Tu nombre',
    otp_title: 'Revisa tu email',
    otp_subtitle: 'Te mandamos un código de verificación',
    otp_placeholder: 'Código de 6 dígitos',
    verify: 'Verificar',
  },
  catalog: {
    greeting: '¡Hola!',
    search_placeholder: 'Buscar maestro o servicio...',
    banner_title: 'Encuentra al maestro perfecto',
    banner_subtitle: 'para tu próximo pololito',
    empty: 'No encontramos maestros con esos filtros',
    empty_cta: 'Limpiar filtros',
  },
  maestro: {
    experiencia: 'años de experiencia',
    trabajos: 'trabajos',
    rating: 'calificación',
    disponible: 'Disponible',
    no_disponible: 'No disponible',
    contactar: 'Contactar',
    llamar: 'Llamar',
    especialidades: 'ESPECIALIDADES',
    calificaciones: 'CALIFICACIONES',
    portafolio: 'PORTAFOLIO',
    zona: 'ZONA DE COBERTURA',
  },
  publish: {
    title: 'Publicar pega',
    form_title: 'Título del trabajo',
    form_title_placeholder: 'Ej: Arreglar llave del baño',
    form_desc: 'Descripción',
    form_desc_placeholder: 'Cuéntale al maestro qué necesitas...',
    form_especialidad: 'ESPECIALIDAD',
    form_ubicacion: 'Ubicación',
    form_ubicacion_placeholder: 'Comuna o dirección',
    form_urgente: 'Es urgente',
    form_fotos: 'Fotos (opcional)',
    form_submit: 'Publicar al tiro',
    feed_title: 'Pegas disponibles',
    feed_empty: 'No hay pegas cerca tuyo por ahora',
    postular: 'Me tinca, postular',
  },
  chat: {
    title: 'Mensajes',
    empty: 'Sin mensajes aún',
    empty_subtitle: 'Contacta un maestro para empezar a chatear',
    input_placeholder: 'Escribe un mensaje...',
    status: {
      nuevo: 'Nuevo',
      en_negociacion: 'En negociación',
      aceptado: 'Aceptado',
      completado: 'Completado',
      rechazado: 'Rechazado',
    },
  },
  profile: {
    edit: 'Editar perfil',
    disponible_toggle: 'Disponible para pegas',
    telefono_toggle: 'Teléfono público',
    mis_direcciones: 'Mis direcciones',
    configuracion: 'Configuración',
    cerrar_sesion: 'Cerrar sesión',
    contratos: 'Contratos',
    calificacion: 'Calificación',
  },
  contact: {
    toast_sent: '¡Solicitud enviada! El maestro te responderá al tiro.',
    toast_accepted: '¡Aceptó tu solicitud! Ya pueden chatear.',
    toast_rejected: 'El maestro rechazó la solicitud.',
    accept: 'Atender',
    reject: 'Rechazar',
  },
  rating: {
    title: '¿Cómo estuvo la pega?',
    calidad: 'Calidad',
    puntualidad: 'Puntualidad',
    comunicacion: 'Comunicación',
    precio: 'Precio',
    comentario_placeholder: 'Cuéntanos tu experiencia (opcional)',
    submit: 'Enviar calificación',
    skip: 'Saltar',
  },
  legal: {
    disclaimer: 'POLOLITOTRABAJOS es solo intermediaria. No garantizamos calidad ni respondemos por incumplimientos, problemas de pago o resultados. Cada usuario es responsable de sus acuerdos. Revisa calificaciones antes de contratar.',
    terms: 'Términos y condiciones',
    privacy: 'Política de privacidad',
  },
} as const;
